todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteView.as_view(), name="delete"),
]

yu2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
]

todo/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Todo(models.Model):
    todo_title = models.CharField("Title", max_length=256, blank=False)
    todo_memo = models.TextField("Descriptions", blank=True)
    todo_visible = models.BooleanField("Visible", default=True)
    published_date = models.DateTimeField(
        "Created time", default=timezone.now, editable=False
    )

    def __str__(self):
        return self.todo_title

todo/forms.py
from django import forms
from .models import Todo


class AddForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = [
            "todo_title",
            "todo_memo",
        ]
        widgets = {
            "todo_title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Title",
                    "size": "60",
                }
            ),
            "todo_memo": forms.Textarea(),
        }
        labels = {"todo_title": "件名", "todo_memo": "メモ"}
        help_texts = {
            "todo_title": "作成するTodoのタイトルを入力",
            "todo_memo": "Todoのメモを入力",
        }
        error_messages = {
            "todo_title": {
                "required": "件名は必須です",
                "max_length": "件名は256文字まで入力できます",
            }
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ["todo_title", "todo_memo", "todo_visible"]
        widgets = {
            "todo_title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Title",
                    "size": "100",
                }
            ),
            "todo_memo": forms.Textarea(attrs={"class": "form-control"}),
            "todo_visible": forms.CheckboxInput(
                attrs={
                    "class": "form-check-input",
                }
            ),
        }
        labels = {
            "todo_title": "件名",
            "todo_memo": "メモ",
            "todo_visible": "表示",
        }

todo/views.py
from .models import Todo
from .forms import AddForm, EditForm

from django.views import generic
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect


# Create your views here.
class IndexView(generic.ListView):
    model = Todo
    context_object_name = "todo_list"
    template_name = "todo/index.html"
    form_class = AddForm

    def get_queryset(self):
        queryset = Todo.objects.all()
        if "visible" in self.request.GET:
            if self.request.GET["visible"] == "open":
                queryset = queryset.filter(todo_visible=True)
            elif self.request.GET["visible"] == "close":
                queryset = queryset.filter(todo_visible=False)
        else:
            queryset = queryset.filter(todo_visible=True)
        if "words" in self.request.GET:
            queryset = queryset.filter(
                todo_title__contains=self.request.GET["words"]
            )
        return queryset.order_by("-published_date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class
        if "visible" in self.request.GET:
            context["visible"] = self.request.GET["visible"]
        if "words" in self.request.GET:
            context["words"] = self.request.GET["words"]
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse("todo:index"))
        else:
            return self.form_invalid(form)


class EditView(generic.UpdateView):
    model = Todo
    template_name = "todo/edit.html"
    form_class = EditForm
    success_url = reverse_lazy("todo:index")


class DeleteView(generic.DeleteView):
    model = Todo
    template_name = "todo/delete.html"
    success_url = reverse_lazy("todo:index")

todo/templates/todo/add.html
{% extends 'todo/base.html' %}

{% block title %}Todo 追加{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">追加</button>
</form>

<hr>

<a href="{% url 'todo:index' %}">戻る</a>
{% endblock %}

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{% block title %}{% endblock %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- <link rel='stylesheet' type='text/css' media='screen' href='main.css'> -->
    <!-- <script src='main.js'></script> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'todo:index' %}">Todo</a>
            <form class="d-flex" method="get" action="{% url 'todo:index' %}">
                <select name="visible" class="form-select me-2">
                    {% if visible == "open" %}
                    <option value="open" selected>OPENから</option>
                    {% else %}
                    <option value="open">OPENから</option>
                    {% endif %}
                    {% if visible == "close" %}
                    <option value="close" selected>CLOSEから</option>
                    {% else %}
                    <option value="close">CLOSEから</option>
                    {% endif %}
                    {% if visible == "all" %}
                    <option value="all" selected>全てから</option>
                    {% else %}
                    <option value="all">全てから</option>
                    {% endif %}
                </select>
                {% if words %}
                <input class="form-control me-2" type="search" placeholder="Search words" size="50" name="words" value="{{ words }}">
                {% else %}
                <input class="form-control me-2" type="search" placeholder="Search words" name="words" size="50">
                {% endif %}
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

todo/templates/todo/delete.html
{% extends 'todo/base.html' %}

{% block title %}Todo 削除{% endblock %}

{% block content %}
<form method="post">
    <p>削除すると元には戻せません。本当に削除しますか？</p>
    {% csrf_token %}
    <button type="submit">削除</button>
</form>

<hr>

<a href="{% url 'todo:index' %}">戻る</a>
{% endblock %}

todo/templates/todo/edit.html
{% extends 'todo/base.html' %}

{% block title %}Todo 編集{% endblock %}

{% block content %}
<div class="d-flex justify-content-end">
    <a class="btn-close mt-5 me-5 border" href="{% url 'todo:index' %}"></a>
</div>
<div class="d-flex justify-content-center m-5">
    <form method="post" action="{% url 'todo:edit' todo.id %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.todo_title.id_for_label }}" class="form-label">Title</label>
            {{ form.todo_title }}
        </div>
        <div class="mb-3">
            <label for="{{ form.todo_memo.id_for_label }}" class="form-label">Description</label>
            {{ form.todo_memo }}
        </div>
        <div class="mb3 form-check form-switch">
            <label for="{{ form.todo_visible.id_for_label }}" class="form-label">Status</label>
            {{ form.todo_visible }}
        </div>
        <div class="d-flex justify-content-center mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
<div class="d-flex justify-content-center">
    <a href="{% url 'todo:delete' todo.id %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block title %}Todo 一覧{% endblock %}

{% block content %}

<!-- 追加フォーム -->
<div class="d-flex justify-content-center my-3">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-auto">
                {{ form.todo_title }}
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </div>
    </form>
</div>

<!-- Todo一覧 -->
{% if todo_list %}
<div class="d-flex flex-wrap justify-content-start my-3">
    {% for todo in todo_list %}
    <div class="card m-2" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ todo.todo_title }}</h5>
            {% if todo.todo_memo %}
            <p class="card-text text-truncate">{{ todo.todo_memo }}</p>
            {% else %}
            <p class="card-text">No info.</p>
            {% endif %}
            <a href="{% url 'todo:edit' todo.id %}" class="btn btn-primary">Edit</a>
            {% if todo.todo_visible == True %}
            <a href="{% url 'todo:edit' todo.id %}" class="btn btn-success">Close</a>
            {% else %}
            <a href="{% url 'todo:edit' todo.id %}" class="btn btn-warning">Reopen</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="d-flex justify-content-center my-3">
    <div class="alert alert-info">Todoがありません</div>
</div>
{% endif %}
{% endblock %}